services:
  db:
    image: mariadb:10.11
    container_name: myblock3-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myblock3_network

# phpMyAdmin 介面
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myblock3-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    depends_on:
      - db
    networks:
      - myblock3_network

  # 2. 後端服務 (Python)
  backend:
    build: 
      context: ./backend
    container_name: myblock3-backend
    restart: always
    ports:
      - "5500:5500"
    depends_on:
      - db  # 確保資料庫先啟動
    environment:
      DB_HOST: db            # 這裡是 service name，不是 localhost
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST} 
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - myblock3_network
      - sso_network

  # 3. 前端服務 (Next.js)
  frontend:
    build:
      context: ./
    container_name: myblock3-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # 如果前端是 SSR，這裡指向後端容器名稱
      NEXT_PUBLIC_API_URL: http://backend:5500
    depends_on:
      - backend
    networks:
      - myblock3_network

volumes:
  db_data:

networks:
  myblock3_network:
    driver: bridge
  sso_network:
    external: true
    name: mylogin2_network